apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: onepanel-additions
subjects:
  - kind: ServiceAccount
    name: admin
    namespace: onepanel
  - kind: ServiceAccount
    name: onepanel
    namespace: onepanel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: onepanel-create-namespace