apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: onepanel
  name: onepanel-cluster-admin
rules:
- apiGroups: [""]
  resources: ["services", "configmaps"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["namespaces", "secrets"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["argoproj.io"]
  resources: ["workflows", "workflowtemplates", "cronworkflows"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: ["onepanel.io"]
  resources: ["workspaces", "workspacetemplates"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["onepanel-service"]
  verbs: ["get", "watch", "list"]