apiVersion: v1
kind: Namespace
metadata:
  name: $(applicationDefaultNamespace) # replace with relevant namespace
  labels:
    istio-injection: enabled
    onepanel.io/enabled: "true"
    onepanel.io/defaultNamespace: "true"