apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - path: storage-class.yaml
    target:
      kind: StorageClass
  - patch: |-
      - op: replace
        path: /metadata/name
        value: onepanel
    target:
      kind: StorageClass