apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: onepanel
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true